version: "3.7"

services:
  app_nginx:
    container_name: redirect_nginx
    #image: fabiocicerchia/nginx-lua:latest
    build:
      context: .docker/nginx
      dockerfile: Dockerfile
    networks:
      - redirect-backend
    working_dir: /app
    volumes:
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./:/app
    depends_on:
      - redirect_php
    ports:
      - 9503:80
      - 8080:8080
    healthcheck:
      test: [ 'CMD', 'curl --fail http://localhost/ || exit 1' ]
      interval: 30s
      timeout: 3s
      retries: 3
    env_file:
      - .env

  redirect_php:
    container_name: ${APP_COMPOSE_PROJECT_NAME}_php_fpm
    build:
      context: ./.docker/php${PHP_VER}-dev-fpm
      args:
        PHP_VER: ${PHP_VER}
    networks:
      - redirect-backend
    env_file:
      - .env
    user: 1000:1000
    ports:
      - "9005:9000"
    environment:
      PHP_IDE_CONFIG: serverName=docker
    volumes:
      - ~/.composer/cache/:/.composer_cache/:rw
      - ./.docker/php7.4-fpm-dev/conf.ini:/usr/local/etc/php/conf.d/conf.ini
      - ./:/app:rw
    working_dir: /app

networks:
  redirect-backend:
    name: redirect-backend
    driver: bridge
