version: "3.7"

services:
  redis_redirect:
    container_name: redis_redirect
    image: redis:alpine
    networks:
      - redirect-backend
    volumes:
      - redis_db:/data
    ports:
      - "127.0.0.1:6381:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 5s
      timeout: 10s
      retries: 5

networks:
  redirect-backend:
    name: redirect-backend
    driver: bridge

volumes:
  #postgres_db:
  redis_db:
