version: "3.7"

services:
  app_nginx:
    container_name: redirect_nginx
    #image: fabiocicerchia/nginx-lua:latest
    build:
      context: .docker/nginx
      dockerfile: Dockerfile
    networks:
      - redirect-backend
    working_dir: /app
    volumes:
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./:/app
    ports:
      - 9503:80
      - 8080:8080
    healthcheck:
      test: [ 'CMD', 'curl --fail http://localhost/ || exit 1' ]
      interval: 30s
      timeout: 3s
      retries: 3

networks:
  redirect-backend:
    name: redirect-backend
    driver: bridge
